/**
 * Create Token View + Static Website Generator.
 *
 * Generates a self-contained static HTML page for a token (metadata,
 * supply, authorities, curve/LP status, social links) that can be hosted on
 * GitHub Pages / IPFS / any static host. Zero browser dependencies at build
 * time — pure HTML string generation.
 * @module
 */

import fs from 'node:fs';
import path from 'node:path';
import type { TokenAudit } from '@solana-toolkit/types';
import { moduleLogger } from '@solana-toolkit/utils';
import type { ServiceContext } from './context.js';

const log = moduleLogger('website-generator');

export interface WebsiteOptions {
  audit: TokenAudit;
  /** Social links shown on the page. */
  links?: { twitter?: string; telegram?: string; website?: string };
  /** Logo URL (default: metadata URI image when available). */
  logoUrl?: string;
  /** Output directory. */
  outDir: string;
  /** Accent color (default #14F195). */
  accent?: string;
}

/**
 * Generates the static token website (index.html + token.json metadata).
 */
export function generateTokenWebsite(opts: WebsiteOptions): { outDir: string; indexHtml: string; metadataJson: string } {
  const accent = opts.accent ?? '#14F195';
  const name = opts.audit.metadata?.name ?? opts.audit.mint.slice(0, 8);
  const symbol = opts.audit.metadata?.symbol ?? '';
  const supply = Number(opts.audit.supplyRaw) / 10 ** opts.audit.decimals;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(name)} (${escapeHtml(symbol)})</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; background:#0b0e14; color:#e6edf3; }
  .wrap { max-width: 720px; margin: 0 auto; padding: 48px 24px; }
  .card { background:#11151f; border:1px solid #21262e; border-radius:16px; padding:28px; margin-bottom:20px; }
  h1 { font-size:32px; margin:0 0 6px; }
  .symbol { color:${accent}; font-weight:700; letter-spacing:1px; }
  .kv { display:grid; grid-template-columns: 160px 1fr; row-gap:10px; font-size:14px; }
  .kv dt { color:#8b949e; }
  .kv dd { margin:0; word-break:break-all; font-family: ui-monospace, SFMono-Regular, monospace; }
  a { color:${accent}; }
  .pill { display:inline-block; padding:2px 10px; border-radius:999px; background:${accent}22; color:${accent}; font-size:12px; margin-right:6px; }
  footer { color:#8b949e; font-size:12px; margin-top:32px; }
</style>
</head>
<body>
<div class="wrap">
  <div class="card">
    <h1>${escapeHtml(name)} <span class="symbol">$${escapeHtml(symbol)}</span></h1>
    ${opts.logoUrl ? `<img src="${escapeHtml(opts.logoUrl)}" alt="logo" style="width:96px;height:96px;border-radius:14px">` : ''}
    <p class="pills">
      <span class="pill">${opts.audit.tokenProgram.includes('2022') ? 'Token-2022' : 'SPL Token'}</span>
      ${opts.audit.mintAuthority ? '<span class="pill">mint authority: SET</span>' : '<span class="pill">mint revoked</span>'}
      ${opts.audit.freezeAuthority ? '<span class="pill">freeze authority: SET</span>' : '<span class="pill">freeze revoked</span>'}
    </p>
  </div>
  <div class="card">
    <dl class="kv">
      <dt>Mint</dt><dd>${escapeHtml(opts.audit.mint)}</dd>
      <dt>Decimals</dt><dd>${opts.audit.decimals}</dd>
      <dt>Total supply</dt><dd>${supply.toLocaleString('en-US')} ${escapeHtml(symbol)}</dd>
      <dt>Metadata URI</dt><dd>${escapeHtml(opts.audit.metadata?.uri ?? '—')}</dd>
      ${opts.audit.transferFeeBps ? `<dt>Transfer fee</dt><dd>${opts.audit.transferFeeBps / 100}%</dd>` : ''}
      ${opts.audit.pumpfun ? `<dt>Bonding curve</dt><dd>${escapeHtml(opts.audit.pumpfun.bondingCurve)}</dd>` : ''}
    </dl>
  </div>
  ${opts.links ? `<div class="card">
    <h3>Community</h3>
    ${opts.links.twitter ? `<p><a href="${escapeHtml(opts.links.twitter)}">X / Twitter</a></p>` : ''}
    ${opts.links.telegram ? `<p><a href="${escapeHtml(opts.links.telegram)}">Telegram</a></p>` : ''}
    ${opts.links.website ? `<p><a href="${escapeHtml(opts.links.website)}">Website</a></p>` : ''}
  </div>` : ''}
  <div class="card">
    <h3>Audit findings</h3>
    <ul>${opts.audit.findings.map((f) => `<li>${escapeHtml(f)}</li>`).join('')}</ul>
  </div>
  <footer>Generated by SolAdmin — self-hosted static page. Verify contracts on-chain; this page is informational only.</footer>
</div>
</body>
</html>
`;

  const metadataJson = JSON.stringify(
    {
      name,
      symbol,
      mint: opts.audit.mint,
      decimals: opts.audit.decimals,
      supply: opts.audit.supplyRaw,
      mintAuthority: opts.audit.mintAuthority,
      freezeAuthority: opts.audit.freezeAuthority,
      metadata: opts.audit.metadata,
      transferFeeBps: opts.audit.transferFeeBps,
      pumpfun: opts.audit.pumpfun,
      generatedAt: new Date().toISOString(),
    },
    null,
    2,
  );

  fs.mkdirSync(path.resolve(opts.outDir), { recursive: true });
  fs.writeFileSync(path.join(opts.outDir, 'index.html'), html, 'utf8');
  fs.writeFileSync(path.join(opts.outDir, 'token.json'), metadataJson, 'utf8');
  log.info({ outDir: opts.outDir }, 'static token website generated');
  return { outDir: opts.outDir, indexHtml: html, metadataJson };
}

/**
 * Convenience: audits a token then generates its website.
 */
export async function generateWebsiteForMint(
  ctx: ServiceContext,
  mint: string,
  outDir: string,
  links?: WebsiteOptions['links'],
): Promise<{ outDir: string; indexHtml: string }> {
  const { auditToken } = await import('./audit.js');
  const audit = await auditToken(ctx, mint);
  return generateTokenWebsite({ audit, outDir, links });
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
